name: The Riace Bronzes
favicon: null
layout_spectrum: 0.24367
typography_spectrum: 0.12146
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fefffa'
    - '#6eb3fb'
    - '#feffff'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
